version: '3.7'
services:
  webapi_dot_net:
    container_name: categorias-subcategorias-webapi
    image: 669335818103.dkr.ecr.us-east-1.amazonaws.com/govco-developers/categorias-subcategorias-webapi:release_production # Old ECR
    # image: 086119512619.dkr.ecr.us-east-1.amazonaws.com/govco-developers/categorias-subcategorias-webapi:release_production # New ECR
    ports:
      - 8087:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=America/Bogota
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    restart: always
    networks:
      - NETWORK_GOVCO_INTERNO
networks:
  NETWORK_GOVCO_INTERNO:
    external: true