version: '3.1'
services:
  webapi_dot_net:
    container_name: categorias_subcategorias_webapi
    image: 669335818103.dkr.ecr.us-east-1.amazonaws.com/govco-developers/categorias-subcategorias-webapi:develop
    ports: 
      - 8087:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=America/Bogota
    restart: always
    networks:
      - NETWORK_GOVCO_INTERNO
networks:
  NETWORK_GOVCO_INTERNO:
    external: true
